// src/utils/factions.js

export const LIGHT_FACTIONS = [
  "Arathorn’s Stand",
  "Army of Dale",
  "Army of Edoras",
  "Army of Erebor",
  "Army of Lake-town",
  "Army of Thrór",
  "Assault on Ravenhill",
  "Atop the Walls",
  "Battle of Bywater",
  "Battle of Fornost",
  "Breaking of the Fellowship",
  "Defenders of Erebor",
  "Defenders of Helm's Deep",
  "Defenders of the Hornburg",
  "Defenders of the Pelennor",
  "Erebor & Dale",
  "Erebor Reclaimed",
  "Fangorn",
  "Fords of Isen",
  "Garrison of Dale",
  "Garrison of Ithilien",
  "Halls of Thranduil",
  "Kingdom of Khazad-dûm",
  "Kingdom of Rohan",
  "Lindon",
  "Lothlórien",
  "Men of the West",
  "Minas Tirith",
  "Númenor",
  "Paths of the Drúadan",
  "Radagast’s Alliance",
  "Rangers of Mirkwood",
  "Realms of Men",
  "Reclamation of Osgiliath",
  "Return of the King",
  "Ride Out",
  "Riders of Éomer",
  "Riders of Théoden",
  "Rivendell",
  "Road to Helm's Deep",
  "Road to Rivendell",
  "Survivors of Lake-town",
  "The Battle of Five Armies",
  "The Beornings",
  "The Eagles",
  "The Fellowship",
  "The Fiefdoms",
  "The Grey Company",
  "The Grief of Éomer",
  "The Iron Hills",
  "The Last Alliance",
  "The Shire",
  "The White Council",
  "Thorin’s Company"
];

export const LIGHT_FACTIONS_LEGEND = [
  "Battle of Greenfields",
  "Expedition to the East",
  "Fields of Celebrant",
  "Reclamation of Moria"
];

export const DARK_FACTIONS = [
  "Army of Carn Dûm",
  "Army of Gothmog",
  "Army of Gundabad",
  "Army of the Great Eye",
  "Army of the White Hand",
  "Assault Upon Helm’s Deep",
  "Azog’s Hunters",
  "Barad-dûr",
  "Besiegers of the Hornburg",
  "Buhrdûr’s Horde",
  "Cirith Ungol",
  "Corsair Fleets",
  "Depths of Moria",
  "Desolator of the North",
  "Dragons of the North",
  "Goblin-town",
  "Grand Army of the South",
  "Harad",
  "Host of the Dragon Emperor",
  "Host of the Witch-king",
  "Legions of Mordor",
  "Lurtz’s Scouts",
  "Minas Morgul",
  "Moria",
  "Muster of Isengard",
  "Pits of Dol Guldur",
  "Rise of the Necromancer",
  "Shadows of Angmar",
  "Sharkey’s Rogues",
  "The Black Gate",
  "The Black Riders",
  "The Easterlings",
  "The Serpent Horde",
  "The Three Trolls",
  "Uglúk’s Scouts",
  "Umbar",
  "Usurpers of Edoras",
  "Wolf Pack of Angmar",
  "Wolves of Isengard",
  "Wraiths on Wings"
];

export const DARK_FACTIONS_LEGEND = [
  "Army of Dunland",
  "Assault on Lothlórien",
  "Far Harad",
  "Fell Beings of Mirkwood",
  "Ravagers of the Shire",
  "The Spider Queen’s Brood",
  "Variags of Khand"
];
